### ISSUE TITLE
Blurry font on macOS Sonoma

### ISSUE THREAD

**Issue by tsengf** [ruphy/speedcrunch#5]
Hi, I noticed that the font is not crisp on Sonoma. Can this be resolved? Thanks.

**Comment by dd23** [comment]
This is a known issue in the old version. It is also discusses here: https://bitbucket.org/heldercorreia/speedcrunch/issues/1106/macos-release-does-not-have-hidpi-enabled

Here's a MacOS release that fixes this: https://github.com/gagarcr/speedcrunch-nightlies/releases/tag/20191205

**Comment by mzaur** [comment]
> This is a known issue in the old version. It is also discusses here: https://bitbucket.org/heldercorreia/speedcrunch/issues/1106/macos-release-does-not-have-hidpi-enabled
> 
> Here's a MacOS release that fixes this: https://github.com/gagarcr/speedcrunch-nightlies/releases/tag/20191205

FYI the official download from the main website is different than this and still has the issue. Both are 0.12 but the official one is 11MB while this version is 44.4MB. This version DOES fix the blurry font issue, but the official version does not.
